"""
Configuration file for the Sphinx documentation builder.

This file configures the Sphinx documentation generator for the DashboardAGTorroni project.
For the full list of built-in configuration values, see:
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

import os
import sys

# -- Path setup --------------------------------------------------------------
# Add the project root directory to the Python path
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../src'))

# -- Project information -----------------------------------------------------
project = 'DashboardAGTorroni'
copyright = '2025, GIACOMO CROCIANI'
author = 'GIACOMO CROCIANI'
release = '1.0.0'
version = '1.0'

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',           # Genera automaticamente documentazione da docstrings
    'sphinx.ext.napoleon',          # Supporto per Google/NumPy style docstrings
    'sphinx.ext.viewcode',          # Aggiunge link al codice sorgente
    'sphinx.ext.intersphinx',       # Link a documentazione esterna
    'sphinx.ext.todo',              # Supporto per TODO
    'sphinx.ext.coverage',          # Controlla copertura documentazione
    'sphinx.ext.mathjax',           # Supporto per formule matematiche
    'sphinx.ext.githubpages',       # Supporto per GitHub Pages
]

# Add any paths that contain templates here, relative to this directory
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The language for content autogenerated by Sphinx
language = 'it'

# -- Options for HTML output -------------------------------------------------
# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Theme options
html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False,
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# The name of an image file (relative to this directory) to place at the top
# of the sidebar
# html_logo = '_static/logo.png'

# The name of an image file (within the static path) to use as favicon
# html_favicon = '_static/favicon.ico'

# -- Options for autodoc ----------------------------------------------------
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# -- Options for napoleon ---------------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None

# -- Options for intersphinx ------------------------------------------------
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'plotly': ('https://plotly.com/python-api-reference/', None),
    'dash': ('https://dash.plotly.com/', None),
}

# -- Options for todo extension ---------------------------------------------
todo_include_todos = True

# -- Additional configuration -----------------------------------------------
# If true, '()' will be appended to :func: etc. cross-reference text
add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::)
add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default
show_authors = True

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting
modindex_common_prefix = ['src.']

# -- Options for LaTeX output -----------------------------------------------
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'preamble': r'''
        \usepackage[utf8]{inputenc}
        \usepackage[italian]{babel}
    ''',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    ('index', 'DashboardAGTorroni.tex', 'DashboardAGTorroni Documentation',
     'GIACOMO CROCIANI', 'manual'),
]

# -- Options for manual page output -----------------------------------------
man_pages = [
    ('index', 'dashboardagtorroni', 'DashboardAGTorroni Documentation',
     [author], 1)
]

# -- Options for Texinfo output ---------------------------------------------
texinfo_documents = [
    ('index', 'DashboardAGTorroni', 'DashboardAGTorroni Documentation',
     author, 'DashboardAGTorroni', 'Interactive dashboard for agricultural data analysis.',
     'Miscellaneous'),
]

# -- Options for Epub output ------------------------------------------------
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# -- Custom configuration ---------------------------------------------------
# Master document
master_doc = 'index'

# Output file base name for HTML help builder
htmlhelp_basename = 'DashboardAGTorronidoc'